### ISSUE TITLE
Fundamental problems importing the library

### ISSUE THREAD

**Issue by machawk1** [campbellr/smashrun-client#2]
I am having an issue importing the client. Here is what I am doing, please advise.

``` shell
$ virtualenv smashrun
New python executable in /private/tmp/smashrun/bin/python2.7
Also creating executable in /private/tmp/smashrun/bin/python
Installing setuptools, pip, wheel...done.
$ source smashrun/bin/activate
(smashrun) $ pip install --pre smashrun-client
Collecting smashrun-client
  Using cached smashrun_client-0.2.0-py2.py3-none-any.whl
Collecting requests-oauthlib (from smashrun-client)
  Downloading requests_oauthlib-0.6.1-py2.py3-none-any.whl
Collecting requests (from smashrun-client)
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 981kB/s 
Collecting oauthlib>=0.6.2 (from requests-oauthlib->smashrun-client)
  Downloading oauthlib-1.1.1.tar.gz (108kB)
    100% |████████████████████████████████| 112kB 1.1MB/s 
Building wheels for collected packages: oauthlib
  Running setup.py bdist_wheel for oauthlib ... done
  Stored in directory: /Users/me/Library/Caches/pip/wheels/c2/d2/a1/0901f53343b65bc0404ed846f7ebde8bc188eb0f56bf030140
Successfully built oauthlib
Installing collected packages: oauthlib, requests, requests-oauthlib, smashrun-client
Successfully installed oauthlib-1.1.1 requests-2.10.0 requests-oauthlib-0.6.1 smashrun-client-0.2.0
(smashrun) $ python
Python 2.7.10 (default, Sep 23 2015, 04:34:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from smashrun import Smashrun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "smashrun.py", line 1, in <module>
    from smashrun import Smashrun
ImportError: cannot import name Smashrun
>>> 
```

**Comment by campbellr** [comment]
Hi @machawk1 

It looks like you have a file `smashrun.py` in your current working directory that is shadowing the installed smashrun package.

Try renaming that file or moving to another directory and trying the import again.

**Comment by machawk1** [comment]
That was it. Thanks @campbellr
